const employees = [
  {
    id: 1,
    name: "Ahmad",
    email: "ahmad@mail.com",
    password: "1234",
    role: "employee",
    taskNumbers: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Update database schema",
        description: "Modify user table to include new fields",
        date: "2025-07-01",
        category: "Database",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Review code submissions",
        description: "Check pull requests for project X",
        date: "2025-07-02",
        category: "Code Review",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix login bug",
        description: "Resolve authentication issue in login module",
        date: "2025-06-28",
        category: "Bug Fix",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Write API documentation",
        description: "Document new endpoints for v2 API",
        date: "2025-07-05",
        category: "Documentation",
      },
    ],
  },
  {
    id: 2,
    name: "Fatima",
    email: "fatima@mail.com",
    password: "1234",
    role: "employee",
    taskNumbers: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Design UI mockups",
        description: "Create wireframes for dashboard redesign",
        date: "2025-07-03",
        category: "UI/UX",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Test payment gateway",
        description: "Integration test with new payment provider",
        date: "2025-06-25",
        category: "Testing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Optimize frontend performance",
        description: "Reduce page load time for main app",
        date: "2025-07-04",
        category: "Performance",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Update user guide",
        description: "Revise user manual for new features",
        date: "2025-07-06",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix CSS bugs",
        description: "Resolve styling issues in mobile view",
        date: "2025-06-29",
        category: "Bug Fix",
      },
    ],
  },
  {
    id: 3,
    name: "Yusuf",
    email: "yusuf@mail.com",
    password: "1234",
    role: "employee",
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 3,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Implement authentication service",
        description: "Set up OAuth2 authentication flow",
        date: "2025-07-02",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Conduct security audit",
        description: "Review application for vulnerabilities",
        date: "2025-07-03",
        category: "Security",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Migrate legacy data",
        description: "Transfer old user data to new system",
        date: "2025-06-27",
        category: "Database",
      },
    ],
  },
  {
    id: 4,
    name: "Aisha",
    email: "aisha@mail.com",
    password: "1234",
    role: "employee",
    taskNumbers: {
      active: 3,
      newTask: 3,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Develop reporting module",
        description: "Create sales report generator",
        date: "2025-07-05",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Update API endpoints",
        description: "Modify existing APIs for new requirements",
        date: "2025-07-04",
        category: "API",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Setup CI/CD pipeline",
        description: "Configure automated deployment",
        date: "2025-06-26",
        category: "DevOps",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Write unit tests",
        description: "Create test cases for payment module",
        date: "2025-07-06",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix memory leak",
        description: "Resolve server memory issue",
        date: "2025-06-28",
        category: "Bug Fix",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Optimize database queries",
        description: "Improve query performance for reports",
        date: "2025-07-07",
        category: "Database",
      },
    ],
  },
  {
    id: 5,
    name: "Omar",
    email: "omar@mail.com",
    password: "1234",
    role: "employee",
    taskNumbers: {
      active: 3,
      newTask: 2,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Create marketing campaign",
        description: "Design email campaign for new product",
        date: "2025-07-03",
        category: "Marketing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Analyze user feedback",
        description: "Compile user survey results",
        date: "2025-07-04",
        category: "Analytics",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Update website content",
        description: "Revise homepage copy",
        date: "2025-06-29",
        category: "Content",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Plan social media posts",
        description: "Schedule posts for next month",
        date: "2025-07-05",
        category: "Social Media",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Test ad campaign",
        description: "Run A/B test for ad creatives",
        date: "2025-06-27",
        category: "Marketing",
      },
    ],
  },
];

const admin = [
  {
    id: 6,
    name: "Awais",
    email: "awais@mail.com",
    password: "1234",
    role: "admin",
  },
];

export const setStorage = () => {
  try {
    localStorage.setItem("employees", JSON.stringify(employees));
    localStorage.setItem("admin", JSON.stringify(admin));
  } catch (error) {
    console.error("Error setting storage:", error);
  }
};

export const getStorage = () => {
  try {
    const employeesData = JSON.parse(localStorage.getItem("employees")) || [];
    const adminData = JSON.parse(localStorage.getItem("admin")) || [];
    return { employees: employeesData, admin: adminData };
  } catch (error) {
    console.error("Error getting storage:", error);
    return { employees: [], admin: [] };
  }
};
